project_name: 'certified-officer-smoke-test'
random_seed: 42
device: 'cuda:0'

data:
  processed_dir: 'data/processed/smoke_test'
  max_samples: 768

models:
  language_model: 'NousResearch/Llama-2-7b-chat-hf'
  encoder_model: 'sentence-transformers/all-MiniLM-L6-v2'
  qlora:
    r: 8
    lora_alpha: 16

training:
  artifacts_dir: 'artifacts/smoke_test'
  epochs: 1
  batch_size: 4
  learning_rate: 5.0e-05
  learning_rate_pg: 2.0e-05
  conformal_alpha: 0.1
  kl_epsilon: 0.1
  kl_lambda: 3.0

evaluation:
  results_dir: '.research/iteration4'
